#!/usr/bin/php
<?php
$dir = dirname($argv[0]);

$f = popen("{$dir}/backuppc-status-json", "r");
$data = "";
while($r = fread($f, 8192))
  $data .= $r;
pclose($f);

$data = json_decode($data, true);

$time = time();

print "Status of all backups:\n\n";

$state_format = array(
  'Status_idle' => "idle",
  'Status_backup_in_progress' => "in progress",
);

printf("%-30s  %6s %12s\n", "Host", "Age", "Status");
foreach($data as $host=>$info) {
  if(array_key_exists('lastGoodBackupTime', $info)) {
    printf("%-30s  %5.1fd %12s\n",
      $host,
      ($time - $info['lastGoodBackupTime']) / 86400.0,
      array_key_exists($info['state'], $state_format) ? $state_format[$info['state']] : $info['state']
    );
  }
}
